### ISSUE TITLE
Apt crashes with Termux proot-distro's new update

### ISSUE THREAD

**Issue by WheezyE** [ZhymabekRoman/proot-static#1]
Hey, I just wanted to report in that I noticed that using proot-static with Termux proot-distro's new Ubuntu-hirsute (which is the only Ubuntu distro available now in proot-distro) causes crashes when I try to update apt.

I'm not sure if this is a proot-static problem or a problem with proot-distro's Ubuntu-hirsute repo but I'm stumped.

Thank you for proot-static, by the way!  It allows me to run box86 on Android via Termux.
More info here: https://github.com/lowspecman420/AnBox86/issues/7

**Comment by ZhymabekRoman** [comment]
Thank you for using proot-static! I'm sorry that I didn't answer for so long. I tried installing proot-distro and the Ubuntu hirsute, and yes indeed, apt update does not work. This problem is already known, and has already been fixed in the latest version of proot. See: https://github.com/termux/proot/issues/172
I will recompile a new version of proot in the next few hours

**Comment by ZhymabekRoman** [comment]
Closed in: https://github.com/ZhymabekRoman/proot-static/commit/f65dc6d469cb08028a1ce303eb5e749fe48756e8

**Comment by WheezyE** [comment]
Thank you for making proot-static!  Have a great week
